{% set name = "environs" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6150ddeb05562a80cc789b308c650d33b98a5f9c3f4c63d9ed465c433f1cb9e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - marshmallow >=3.13.0
    - python-dotenv

test:
  imports:
    - environs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - jan-janssen
    - mcs07
