{% set name = "environs" %}
{% set version = "14.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7b8f6fcf3301bc674bc9c03e39b5986d116126ffb96764efd34c339ed9464ee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - typing_extensions
    - python >={{ python_min }}
    - marshmallow >=3.18.0
    - python-dotenv

test:
  imports:
    - environs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - jan-janssen
    - mcs07
