{% set name = "environs" %}
{% set version = "11.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e068ae3174cef52ba4b95ead22e639056a02465f616e62323e04ae08e86a75a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - flit
  run:
    - python >=3.5
    - marshmallow >=3.13.0
    - python-dotenv

test:
  imports:
    - environs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sloria/environs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  dev_url: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - jan-janssen
    - mcs07
