schema_version: 1

context:
  name: environs
  version: 15.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1bfc0d32b43692f28a6e294ad2b69903d43a214672ebcf3124a66d66b52b2418

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit
  run:
    - typing_extensions
    - python >=${{ python_min }}
    - marshmallow >=4.0.0
    - python-dotenv

tests:
  - python:
      imports:
        - environs
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: Simplified environment variable parsing
  homepage: https://github.com/sloria/environs
  repository: https://github.com/sloria/environs

extra:
  recipe-maintainers:
    - jan-janssen
    - mcs07
